/*

Custom script

This file will not be overwritten by the updater

*/

// JavaScript code
function search_animal() {
  let input = document.getElementById("searchbar").value;
  input = input.toLowerCase();
  let x = document.getElementsByClassName("animals");

  for (i = 0; i < x.length; i++) {
    if (!x[i].innerHTML.toLowerCase().includes(input)) {
      x[i].style.display = "none";
    } else {
      x[i].style.display = "block";
    }
  }
}



(function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i+"?ref=bwt";
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "ua7oiz2cxt");


    (function () {
  const NEW_HOME = "https://pizzaedition.pro";
  const NEW_GAME_BASE = NEW_HOME + "/g/";
  const NEW_CATEGORY_BASE = NEW_HOME + "/category/";

  /* ✅ VALID GAMES (slug only) */
  const validGames = new Set([
    "level-devil",
"1v1lol",
"10-minutes-till-dawn",
"escape-road",
"burnout-drift-seaport-max",
"dragon-world",
"bowling-stars",
"cat-gunner-super-zombie-shoot",
"cluster-rush",
"fortz",
"gold-digger-frvr",
"gladihoppers",
"bearsus",
"zombie-derby-pixel-survival",
"zombs-royale-io",
"fortnite",
"basket-random",
"11-11",
"1010-color-match",
"subway-surfers",
"12-minibattles",
"18-wheeler-cargo-simulator",
"18-wheeler-cargo-simulator-2",
"2048-multitask",
"3d-car-simulator",
"3d-moto-simulator-2",
"4th-and-goal-2022",
"4x4-drive-offroad",
"8-ball-pool",
"a-dance-of-fire-and-ice",
"a-small-world-cup",
"adventure-drivers",
"agar-io",
"age-of-war",
"air-hockey-championship-deluxe",
"among-us",
"apple-shooter",
"apple-worm",
"aqua-thrills",
"archery-world-tour",
"arithmetica",
"athletics-hero",
"awesome-tanks-2",
"basket-and-ball",
"basket-battle",
"basket-bros",
"basket-champs",
"basket-monsterz",
"2048",
"basket-slam-dunk-2",
"basket-swooshes",
"basket-swooshes-plus",
"basketball-clash",
"basketball-frvr",
"basketball-io",
"basketball-king",
"basketball-league",
"basketball-legends-2020",
"basketball-line",
"basketball-orbit",
"basketball-serial-shooter",
"basketball-skills",
"basketball-slam-dunk",
"basketball-stars",
"basketball-superstars",
"basketbros",
"battle-wheels",
"big-shot-boxing",
"big-tall-small",
"bike-trials-offroad-1",
"bike-trials-winter-1",
"bike-trials-winter-2",
"bitlife",
"block-blast",
"block-the-pig",
"blocky-cars",
"blocky-trials",
"blumgi-ball",
"blumgi-castle",
"blumgi-paintball",
"blumgi-rocket",
"blumgi-rocket",
"blumgi-soccer",
"bob-the-robber-2",
"bob-the-robber-4",
"bomb-it-7",
"bouncy-basketball",
"bouncy-dunk",
"boxing-physics-2",
"boxing-random",
"brain-for-monster-truck",
"brain-test-2-tricky-stories",
"brain-test-3-tricky-quests",
"brain-test-tricky-puzzles",
"breaking-the-bank",
"bubble-trouble",
"bubble-trouble-3",
"bullet-force",
"bumper-cars-soccer",
"bunny-hop",
"burger-bounty",
"burnin-rubber-5-xs",
"burnin-rubber-crash-n-burn",
"burrito-bison",
"candy-jump",
"cannon-basketball",
"cannon-basketball-2",
"cannon-basketball-3",
"cannon-basketball-4",
"cannon-strike",
"car-climb-racing",
"car-rush",
"cars-thief",
"cars-thief-tank-edition",
"cat-trap",
"cats",
"chicken-merge",
"choppy-orc",
"city-bike-stunt-2",
"city-car-driving-stunt-master",
"city-rider",
"color-switch",
"color-tunnel-2",
"cookie-clicker",
"crazy-ball-3d",
"crazy-cars",
"crazy-tunnel-3d",
"cricket-world-cup",
"crossy-road",
"cubes-king",
"cubito-mayhem",
"curve-ball-3d",
"cyber-cars-punk-racing",
"death-chase",
"death-run-3d",
"deepest-sword",
"deer-simulator",
"demolition-derby-crash-racing",
"detective-loupe-puzzle",
"dinosaur-game",
"dog-simulator-3d",
"doodle-champion-island",
"doodle-jump",
"draw-the-hill",
"dreadhead-parkour",
"drift-hunters",
"drift-boss",
"drive-mad",
"drunken-duel",
"duck-life",
"duck-life-2-world-champion",
"duck-life-3-evolution",
"duck-life-4",
"dune-game",
"dunkbrush",
"dunker",
"dunker-2",
"dunkers",
"earn-to-die",
"eggy-car",
"electron-dash",
"energy",
"epic-basketball",
"escaping-the-prison",
"eugenes-life",
"evo-city-driving",
"extreme-car-driving-simulator",
"extreme-car-parking",
"factory-balls-forever",
"fairy-dressup",
"fancy-pants-2",
"fancy-pants-3",
"fireboy-and-watergirl",
"five-nights-at-freddys",
"five-nights-at-freddys-2",
"five-nights-at-freddys-3",
"flappy-bird",
"flappy-dunk",
"fleeing-the-complex",
"flipper-dunk-3d",
"flying-car-simulator",
"foot-chinko",
"football-legends",
"football-masters",
"free-kick-shooter",
"free-the-key",
"friday-night-funkin",
"funny-shooter-2",
"furious-racing-3d",
"g-switch-3",
"geometry-dash",
"getaway-shootout",
"go-kart-go-ultra",
"gobble",
"golf-champions",
"golfinity",
"google-feud",
"google-snake",
"grand-prix-hero",
"granny",
"gravity-soccer",
"grindcraft-remastered",
"gun-mayhem-3",
"gunspin",
"hammer-2-reloaded",
"happy-room",
"happy-wheels",
"head-basketball",
"head-soccer-2023",
"heads-arena-soccer-all-stars",
"heart-star-html5",
"hextris",
"highway-racer-3d",
"highway-rider-extreme",
"highway-traffic",
"hill-climb-racing",
"hill-climb-racing-2",
"hoop-world-3d",
"horse-shoeing",
"horse-simulator-3d",
"house-of-hazards",
"hover-racer",
"hover-racer-drive",
"icy-purple-head-3",
"idle-ants",
"idle-breakout",
"idle-dice",
"idle-digging-tycoon",
"idle-lumber-inc",
"idle-miner",
"idle-mining-empire",
"idle-startup-tycoon",
"impossible-monster-truck-race",
"impossible-tic-tac-toe",
"infinity-loop",
"iron-snout",
"jelly-truck",
"jetpack-joyride",
"johnny-upgrade",
"jollyworld",
"jump-up-3d",
"jump-up-3d-mini-basketball",
"jumping-shell",
"kart-race-3d",
"kawaii-dressup",
"kix-dream-soccer",
"leader-strike",
"life-the-game",
"linebacker-alley-2",
"mad-day",
"mad-truck-challenge-special",
"madalin-stunt-cars-2",
"madalin-stunt-cars-3",
"marble-dash",
"masked-forces",
"master-chess",
"maze-path-of-light",
"maze-planet-3d",
"merge-cakes",
"merge-cyber-racers",
"merge-harvest",
"merge-round-racers",
"microwars",
"minecraft",
"minesweeper",
"minibattles",
"mob-city",
"monster-tracks",
"monsters-wheels-special",
"mosaic-puzzle-art",
"moto-maniac",
"moto-maniac-2",
"moto-road-rash-3d",
"moto-trial-racing-2",
"moto-x3m",
"moto-x3m-2",
"moto-x3m-pool-party",
"moto-x3m-spooky-land",
"moto-x3m-winter",
"murder",
"my-pony-my-little-race",
"n-gon",
"neon-war",
"noob-basketball-clicker",
"noob-drive",
"offroader-v5",
"orbital-survival",
"ovo",
"panda-bubble-shooter",
"panda-simulator-3d",
"papas-pizzeria",
"paper-fighter-3d",
"paper-io-2",
"parking-fury",
"parking-fury-2",
"parking-fury-3d-bounty-hunter",
"parking-fury-3d-night-thief",
"penalty-kick-online",
"penalty-shooters-2",
"perfect-peel",
"ping-pong-html5",
"pixel-gun-survival",
"pixwars-2",
"plactions",
"poly-track",
"pool-club",
"poor-bunny",
"pop-it-master",
"power-badminton",
"puppet-master",
"rabbit-samurai",
"race-survival",
"raft-wars",
"raft-wars-2",
"raft-wars-multiplayer",
"rally-champion",
"real-cars-in-city",
"real-city-driving-2",
"real-simulator-monster-truck",
"recoil",
"red-ball-4",
"retro-bowl",
"retro-bowl-college",
"riddle-school",
"rio-rex",
"rocket-pult",
"rocket-soccer-derby",
"rogue-dunk",
"rolly-vortex",
"roly-poly-monsters",
"rooftop-snipers",
"rooftop-snipers-2",
"roper",
"rowdy-city-wrestling",
"rowdy-wrestling",
"run-3",
"run-3-editor",
"running-fred",
"rusher-crusher",
"sausage-flip",
"school-bus-demolition-derby",
"scrap-metal",
"shell-shockers",
"short-life",
"short-ride",
"shortcut-race",
"sketchbook-04",
"skiing-fred",
"slime-road",
"slither-io",
"slope",
"slope-2-multiplayer",
"slope-3",
"slope-city",
"slope-tunnel",
"smash-karts",
"sniper-gun-shooting",
"snow-rider-3d",
"soccar",
"soccer-random",
"soccer-skills-champions-league",
"soccer-skills-euro-cup",
"soccer-skills-world-cup",
"solitaire",
"speed-boat-extreme-racing",
"squish-run",
"stack",
"stack-ball",
"stack-bump-3d",
"stacktris",
"stair-race-3d",
"stealing-the-diamond",
"stick-defenders",
"stick-fighter",
"stick-merge",
"stickman-army-team-battle",
"stickman-army-the-resistance",
"stickman-bike",
"stickman-bike-pr",
"stickman-boxing-ko-champion",
"stickman-bridge-constructor",
"stickman-climb-2",
"stickman-fighter-epic-battle-2",
"stickman-fighter-mega-brawl",
"stickman-golf",
"stickman-hook",
"stickman-ragdoll-crash-fun",
"stickman-school-run",
"stock-car-hero",
"street-ball-jam",
"street-ball-star",
"striker-dummies",
"stunt-car-challenge-3",
"stupid-zombies",
"subway-runner",
"subway-surfers-beijing",
"subway-surfers-houston",
"subway-surfers-monaco",
"subway-surfers-newyork",
"super-bike-the-champion",
"super-hexbee-merger",
"super-hot",
"super-liquid-soccer",
"super-mario-bros",
"super-racing-gt-drag-pro",
"super-santa-kicker",
"super-star-car",
"super-tunnel-rush",
"superbattle-2",
"superbike-hero",
"survivor-in-rainbow-monster",
"swatforce-vs-terrorists",
"swingo",
"tag",
"tanuki-sunset",
"tap-tap-shots",
"temple-of-boom",
"temple-run-2",
"tennis-masters",
"tetris",
"tetris-flash",
"the-impossible-quiz",
"the-little-giant",
"the-spear-stickman",
"there-is-no-game",
"thumb-fighter",
"thumb-fighter-christmas",
"tictactoe",
"tiger-simulator-3d",
"tiny-fishing",
"tinytownracing",
"tomb-of-the-mask",
"tomb-of-the-mask-color",
"toon-off",
"top-speed-3d",
"top-speed-racing-3d",
"tower-of-destiny",
"traffic-mania",
"traffic-rider",
"tricks",
"truck-traffic",
"tube-jumpers",
"tunnel-rush",
"turbo-moto-racer",
"two-ball-3d-dark",
"two-neon-boxes",
"ultimate-car-driving",
"unicycle-hero",
"vex-4",
"vex-5",
"vex-6",
"vex-7",
"volley-random",
"volleyball-challenge",
"water-color-sort",
"we-become-what-we-behold",
"where-is-my-cat",
"who-is",
"wizard-mike",
"wood-blocks-3d",
"word-city-crossed",
"word-city-uncrossed",
"wordle-unlimited",
"words-search-classic-edition",
"worlds-hardest-game",
"worlds-hardest-game-2",
"worlds-hardest-game-3",
"wormate-io",
"wrassling",
  ]);

  
  /* ✅ VALID CATEGORIES */
  const validCategories = new Set([
    "action","adventure","arcade","basketball-games","bike","boys-games",
    "car","fighting","girls-games","horror","idle","io-games","multiplayer",
    "platformer","puzzle","racing","running","shooting","simulator",
    "skill","sports","strategy"
  ]);

  const path = window.location.pathname.toLowerCase();

  /* 🎮 GAME PAGES */
  if (path.startsWith("/game/") && path.endsWith(".html")) {
    const slug = path.replace("/game/","").replace(".html","");
    if (validGames.has(slug)) {
      location.replace(NEW_GAME_BASE + slug + "/");
    } else {
      location.replace(NEW_HOME);
    }
    return;
  }

  /* 🗂️ CATEGORY PAGES */
  if (path.startsWith("/category/") && path.endsWith(".html")) {
    const slug = path.replace("/category/","").replace(".html","");
    if (validCategories.has(slug)) {
      location.replace(NEW_CATEGORY_BASE + slug + "/");
    } else {
      location.replace(NEW_HOME);
    }
    return;
  }

  /* 📄 OTHER HTML / APPS / RANDOM */
  if (
    path.startsWith("/apps/") ||
    path.endsWith(".html")
  ) {
    location.replace(NEW_HOME);
    return;
  }

  /* 🏠 ROOT */
  if (path === "/" || path === "/index.html") {
    location.replace(NEW_HOME);
  }
})();